spring:
  application:
    name: vektor-mail

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    de.vektor: DEBUG
    org.apache.felix: INFO
